plugins {
    id 'java-library'
}

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}

dependencies {
    api 'com.google.guava:guava:32.1.1-jre'
    implementation("com.google.guava:guava:32.1.1-jre")
    ext.checkerFrameworkVersion = '0.6.3'
    implementation "org.checkerframework:checker-qual:${checkerFrameworkVersion}"
    //annotationProcessor "org.checkerframework:checker:${checkerFrameworkVersion}"
}