package com.tbohne.llkpattern.unicodeanalyzer;

import com.google.common.collect.Range;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.function.IntPredicate;

public class UnicodeAnalyzer {

	public static void main(String[] args) {
		printHeader();
		intPredicate("isValidCodePoint", Character::isValidCodePoint);
		intPredicate("isBmpCodePoint", Character::isBmpCodePoint);
		intPredicate("isSupplementaryCodePoint", Character::isSupplementaryCodePoint);
		intPredicate("isLowerCase", Character::isLowerCase);
		intPredicate("isUpperCase", Character::isUpperCase);
		intPredicate("isTitleCase", Character::isTitleCase);
		intPredicate("isDigit", Character::isDigit);
		intPredicate("isDefined", Character::isDefined);
		intPredicate("isLetter", Character::isLetter);
		intPredicate("isLetterOrDigit", Character::isLetterOrDigit);
		intPredicate("isAlphabetic", Character::isAlphabetic);
		intPredicate("isIdeographic", Character::isIdeographic);
		intPredicate("isJavaIdentifierStart", Character::isJavaIdentifierStart);
		intPredicate("isJavaIdentifierPart", Character::isJavaIdentifierPart);
		intPredicate("isUnicodeIdentifierStart", Character::isUnicodeIdentifierStart);
		intPredicate("isUnicodeIdentifierPart", Character::isUnicodeIdentifierPart);
		intPredicate("isIdentifierIgnorable", Character::isIdentifierIgnorable);
		intPredicate("isSpaceChar", Character::isSpaceChar);
		intPredicate("isWhitespace", Character::isWhitespace);
		intPredicate("isISOControl", Character::isISOControl);
		intPredicate("isMirrored", Character::isMirrored);

		categories();
		scripts();
		blocks();
		printFooter();
	}

	public static void printHeader() {
		System.out.print("package com.tbohne.llkpattern;\n\n");
		System.out.print("import javax.annotation.processing.Generated;\n\n");
		System.out.print("/**\n");
		System.out.print(" * ⚠️ DO NOT EDIT THIS FILE DIRECTLY ⚠️\n");
		System.out.print(" *\n");
		System.out.print(" * <p>Generated by {@code UnicodeAnalyzer} (see the {@code unicodeanalyzer} module) from the\n");
		System.out.print(" * running JDK's own {@link Character} tables. Any changes made directly to this file will be\n");
		System.out.print(" * lost the next time it is regenerated -- {@code UnicodeAnalyzer} is run manually, as needed\n");
		System.out.print(" * (e.g. after a JDK upgrade changes Unicode data), not as part of the normal build.\n");
		System.out.print(" */\n");
		System.out.printf("@Generated(value = \"com.tbohne.llkpattern.unicodeanalyzer.UnicodeAnalyzer\", date = \"%s\")\n", LocalDate.now());
		System.out.print("class UnicodePredicates {\n");
		printCodePointMap("ascii", java.util.List.of(Range.closedOpen(0x0, 0x80)));
	}

	public static void printFooter() {
		System.out.print("}\n");
	}

	public static void intPredicate(String name, IntPredicate predicate) {
		// Emitted as its own method (rather than inline in the field initializer) so that this
		// field's builder chain doesn't count against the class's single shared <clinit> method,
		// which has a 64KB bytecode limit that the combined initializers of ~1000 fields exceed.
		// See UnicodePredicates.java, and remaining_work.md "code too large".
		List<Range<Integer>> ranges = new ArrayList<>();
		int i=0;
		while (i<=0x10FFFF) {
			while (i<=0x10FFFF && !predicate.test(i))
				++i;
			int min = i;
			while (i<=0x10FFFF && predicate.test(i))
				++i;
			int max = i;
			if (min < max) {
				ranges.add(Range.closedOpen(min, max));
			}
		}
		printCodePointMap(name, ranges);
	}

	public static void categories() {
		Map<Byte, Set<Range<Integer>>> ranges = new HashMap<>(31);
		for (byte j=0; j<31; j++) {
			ranges.put(j, new HashSet<>());
			}
		int i=0;
		while (i<=0x10FFFF) {
			int min = i;
			byte category = (byte) Character.getType(i);
			i++;
			while (i<=0x10FFFF && Character.getType(i) == category)
				++i;
			int max = i;
			ranges.get(category).add(Range.closedOpen(min, max));
		}
		printRanges("UNASSIGNED", ranges.get(Character.UNASSIGNED));
		printRanges("UPPERCASE_LETTER", ranges.get(Character.UPPERCASE_LETTER));
		printRanges("LOWERCASE_LETTER", ranges.get(Character.LOWERCASE_LETTER));
		printRanges("TITLECASE_LETTER", ranges.get(Character.TITLECASE_LETTER));
		printRanges("MODIFIER_LETTER", ranges.get(Character.MODIFIER_LETTER));
		printRanges("OTHER_LETTER", ranges.get(Character.OTHER_LETTER));
		printRanges("NON_SPACING_MARK", ranges.get(Character.NON_SPACING_MARK));
		printRanges("ENCLOSING_MARK", ranges.get(Character.ENCLOSING_MARK));
		printRanges("COMBINING_SPACING_MARK", ranges.get(Character.COMBINING_SPACING_MARK));
		printRanges("DECIMAL_DIGIT_NUMBER", ranges.get(Character.DECIMAL_DIGIT_NUMBER));
		printRanges("LETTER_NUMBER", ranges.get(Character.LETTER_NUMBER));
		printRanges("OTHER_NUMBER", ranges.get(Character.OTHER_NUMBER));
		printRanges("SPACE_SEPARATOR", ranges.get(Character.SPACE_SEPARATOR));
		printRanges("LINE_SEPARATOR", ranges.get(Character.LINE_SEPARATOR));
		printRanges("PARAGRAPH_SEPARATOR", ranges.get(Character.PARAGRAPH_SEPARATOR));
		printRanges("CONTROL", ranges.get(Character.CONTROL));
		printRanges("FORMAT", ranges.get(Character.FORMAT));
		printRanges("PRIVATE_USE", ranges.get(Character.PRIVATE_USE));
		printRanges("SURROGATE", ranges.get(Character.SURROGATE));
		printRanges("DASH_PUNCTUATION", ranges.get(Character.DASH_PUNCTUATION));
		printRanges("START_PUNCTUATION", ranges.get(Character.START_PUNCTUATION));
		printRanges("END_PUNCTUATION", ranges.get(Character.END_PUNCTUATION));
		printRanges("CONNECTOR_PUNCTUATION", ranges.get(Character.CONNECTOR_PUNCTUATION));
		printRanges("OTHER_PUNCTUATION", ranges.get(Character.OTHER_PUNCTUATION));
		printRanges("MATH_SYMBOL", ranges.get(Character.MATH_SYMBOL));
		printRanges("CURRENCY_SYMBOL", ranges.get(Character.CURRENCY_SYMBOL));
		printRanges("MODIFIER_SYMBOL", ranges.get(Character.MODIFIER_SYMBOL));
		printRanges("OTHER_SYMBOL", ranges.get(Character.OTHER_SYMBOL));
		printRanges("INITIAL_QUOTE_PUNCTUATION", ranges.get(Character.INITIAL_QUOTE_PUNCTUATION));
		printRanges("FINAL_QUOTE_PUNCTUATION", ranges.get(Character.FINAL_QUOTE_PUNCTUATION));
	}

		public static void scripts() {
			Map<Character.UnicodeScript, Set<Range<Integer>>> ranges = new HashMap<>(200);
			for (Character.UnicodeScript script : Character.UnicodeScript.values()) {
				ranges.put(script, new HashSet<>());
			}
			int i=0;
			while (i<=0x10FFFF) {
				int min = i;
				Character.UnicodeScript script = Character.UnicodeScript.of(i);
				i++;
				while (i<=0x10FFFF && Character.UnicodeScript.of(i) == script)
					++i;
				int max = i;
				ranges.get(script).add(Range.closedOpen(min, max));
			}
			for (Character.UnicodeScript script : Character.UnicodeScript.values()) {
				printRanges(script.name(), ranges.get(script));
			}
		}

	public static void blocks() {
		Map<Character.UnicodeBlock, Set<Range<Integer>>> ranges = new HashMap<>(700);
		int i=0;
		while (i<=0x10FFFF) {
			int min = i;
			Character.UnicodeBlock block = Character.UnicodeBlock.of(i);
			i++;
			while (i<=0x10FFFF && Character.UnicodeBlock.of(i) == block)
				++i;
			int max = i;
			ranges.getOrDefault(block, new HashSet<>()).add(Range.closedOpen(min, max));
		}
		for (Map.Entry<Character.UnicodeBlock, Set<Range<Integer>>> entry : ranges.entrySet()) {
			printRanges(entry.getKey().toString(), entry.getValue());
		}
	}

	public static void printRanges(String name, Set<Range<Integer>> rangeSet) {
		// rangeSet comes out of a HashMap/HashSet, so it arrives in no particular order --
		// CodePointMap.MutableCodePointMap#appendSorted requires ascending min (see
		// printCodePointMap), unlike the old ImmutableRangeSet.Builder this replaced.
		List<Range<Integer>> ranges = new ArrayList<>(rangeSet);
		ranges.sort(Comparator.comparing(Range::lowerEndpoint));
		printCodePointMap(name, ranges);
	}

	/**
	 * Emits one {@code private static CodePointMap<Boolean> init_NAME()}/{@code static final
	 * CodePointMap<Boolean> NAME} field pair, built via {@code ArrayCodePointMap#appendSorted}.
	 * {@code ranges} must already be in ascending {@code min} order and pairwise disjoint -- see
	 * the comment in intPredicate() for why each field gets its own method (the shared
	 * {@code <clinit>}'s 64KB bytecode limit).
	 */
	public static void printCodePointMap(String name, List<Range<Integer>> ranges) {
		System.out.printf("private static CodePointMap<Boolean> init_%s() {\n", name);
		System.out.print("\tArrayCodePointMap<Boolean> result = new ArrayCodePointMap<>();\n");
		System.out.printf("\tresult.ensureCapacity(%d);\n", ranges.size());
		for (Range<Integer> range : ranges) {
			System.out.printf("\tresult.appendSorted(0x%x, 0x%x, Boolean.TRUE);\n", range.lowerEndpoint(), range.upperEndpoint());
		}
		System.out.print("\treturn result;\n");
		System.out.print("}\n");
		System.out.printf("static final CodePointMap<Boolean> %s = init_%s();\n\n", name, name);
	}
}
